server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

socket-server:
  host: ${SOCKET_SERVER_HOST:0.0.0.0}
  port: ${SOCKET_SERVER_PORT:9999}

client:
  url: ${CLIENT_URL:http://localhost:3000}

spring:
  # JACKSON CONFIG
  jackson:
    serialization:
      write-dates-as-timestamps: false

  # APPLICATION CONFIG
  application:
    name: Zola
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # REDIS  CONFIG
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:123456}
      repositories:
        enabled: false

  # DATASOURCE CONFIG
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/Zola}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  # JPA/HIBERNATE CONFIG
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT CONFIG
jwt:
  accessSignerKey: ${JWT_ACCESS_SIGNER_KEY}
  refreshSignerKey: ${JWT_REFRESH_SIGNER_KEY}
  valid-duration: ${JWT_VALID_DURATION:3600}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:604800}

# MAIL CONFIG (Brevo)
email:
  host: ${EMAIL_HOST:https://api.brevo.com}
  api-key: ${EMAIL_API_KEY}
  endpoint: /v3/smtp/email
  sender:
    email: ${EMAIL_SENDER_EMAIL}
    name: ${EMAIL_SENDER_NAME}

otp:
  expiration: ${OTP_EXPIRATION:5}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

open:
  api:
    title: "Zola API"
    version: "v1.0.0"
    description: "API for Zola Application."
    server:
      url: "http://localhost:8080/api"
      description: "Local Server."
    group:
      package-to-scan: "com.zola.controllers"

init:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin}
    email: ${ADMIN_EMAIL:admin@gmail.com}
    phone: ${ADMIN_PHONE:0354802825}

app:
  default-avatar-url: ${DEFAULT_AVATAR_URL:https://static.vecteezy.com/system/resources/thumbnails/001/840/618/small/picture-profile-icon-male-icon-human-or-people-sign-and-symbol-free-vector.jpg}